Repository findologic/plugin-shopware-5, pull requests merged in 2018-08, with the labels that each got.

#92 Check if manufacturer exists first
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#94 Fetch only active products from database
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/ShopwareProcess.php
Labels: bug, next release

#99 Fix travis build
  .travis.yml
Labels: bug, next release

#96 Update libflexport to fix integration issue with keywords
  FinSearchUnified/composer.json
  FinSearchUnified/composer.lock
Labels: bug, next release

#100 Rename variable and cast parameters to integer
  FinSearchUnified/Controllers/Frontend/Findologic.php
Labels: next release

#104 Handle vendor filter
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#98 Respect property setting filterable
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: enhancement, next release

#105 Rename catFilter so SW can handle it
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug, next release

#108 Prevent duplicate filter values
  FinSearchUnified/Helper/StaticHelper.php
Labels: bug, next release

#107 Rework fallback search check
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug, next release

#109 Check if parameter is already present
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#93 Deactivate customization plugins of FINDOLOGIC
  FinSearchUnified/FinSearchUnified.php
Labels: enhancement, next release
