Repository findologic/plugin-shopware-5, pull requests merged in 2018-10, with the labels that each got.

#130 160916433 invalidate product stream cache
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/ShopwareProcess.php
Labels: bug, next release

#131 160659247 alive test
  FinSearchUnified/Helper/UrlBuilder.php
Labels: enhancement, next release

#132 Add readonly field to config page
  FinSearchUnified/Constants.php
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/config.xml
Labels: enhancement, next release

#133 161015682 translated variations
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/ShopwareProcess.php
Labels: bug, next release

#134 161082205 add properties to export data
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#136 Handle null values
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug

#138 Update integration label
  FinSearchUnified/Constants.php
Labels: next release

#141 160952280 handle invalid characters
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/Helper/StaticHelper.php
Labels: bug, next release

#143 Remove code paths
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#142 Test Travis CI Setup
  .travis.yml
  FinSearchUnified/tests/PluginTest.php
Labels: next release

#140 161021154 send navigation requests
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#139 Handle requests for match count
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#145 Fix hex values for umlaut characters
  FinSearchUnified/Helper/StaticHelper.php
Labels: bug, next release
