Repository findologic/plugin-shopware-5, pull requests merged in 2018-12, with the labels that each got.

#167 Sw 152 rewrite shopware process
  FinSearchUnified/Bundles/SearchBundle/Condition/HasActiveCategoryCondition.php
  FinSearchUnified/Bundles/SearchBundle/Condition/HasActiveChildOfShopCategoryCondition.php
  FinSearchUnified/Bundles/SearchBundleDBAL/Condition/HasActiveCategoryConditionHandler.php
  FinSearchUnified/Bundles/SearchBundleDBAL/Condition/HasActiveChildOfShopCategoryConditionHandler.php
  FinSearchUnified/BusinessLogic/Export.php
  FinSearchUnified/Resources/services/services.xml
  FinSearchUnified/tests/Bundles/SearchBundle/Condtion/HasActiveCategoryConditionHandlerTest.php
  FinSearchUnified/tests/Bundles/SearchBundle/Condtion/HasActiveChildOfShopCategoryConditionHandlerTest.php
  FinSearchUnified/tests/BusinessLogic/ExportTest.php
  FinSearchUnified/tests/Helper/Utility.php
  FinSearchUnified/tests/PluginTest.php
Labels: enhancement

#166 [BUGFIX] SW-215 trim category names
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#165 Sw 216 fix sitemap cronjob
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/Components/ProductStream/CriteriaFactory.php
  FinSearchUnified/Components/ProductStream/Repository.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
  FinSearchUnified/composer.lock
Labels: bug, next release

#168 SW-213 build script for packaging repository
  FinSearchUnified/composer.json
  archive.sh
Labels: enhancement, next release

#169 SW-218 Filter user IPs if they are duplicate in the environment variable
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: bug, next release
