Repository findologic/plugin-shopware-5, pull requests merged in 2018-11, with the labels that each got.

#149 Set view directory at a single place
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Resources/services/services.xml
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug

#151 Decode values from Smart Suggest
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug, next release

#150 161543166 show frequency
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/config.xml
Labels: enhancement, next release

#152 Initialize array on each iteration
  FinSearchUnified/Helper/StaticHelper.php
Labels: bug, next release

#159 Sw 211 test criteria factory product stream
  FinSearchUnified/tests/Components/ProductStream/CriteriaFactoryTest.php
Labels: enhancement, next release

#160 Skip FINDOLOGIC search for manufacturer pages
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug, next release

#157 Build redirect URI based on base URL
  FinSearchUnified/Subscriber/Frontend.php
Labels: bug, next release

#158 Skip products without valid ordernumber
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#155 Sw 214 code style checks
  .travis.yml
  FinSearchUnified/Bundles/FacetResult/ColorPickerFacetResult.php
  FinSearchUnified/Bundles/FindologicFacetGateway.php
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/BusinessLogic/FindologicArticleFactory.php
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Components/ProductStream/Repository.php
  FinSearchUnified/Constants.php
  FinSearchUnified/Controllers/Api/Findologic.php
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Subscriber/Api.php
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Subscriber/RegisterComponents.php
  FinSearchUnified/Subscriber/ServiceSubscriber.php
  FinSearchUnified/XmlInformation.php
  FinSearchUnified/composer.json
  FinSearchUnified/composer.lock
  FinSearchUnified/phpunit.xml.dist
  FinSearchUnified/shopware-phpcs.xml
  FinSearchUnified/tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/tests/Functional/Bootstrap.php
  FinSearchUnified/tests/Helper/StaticHelperTest.php
  FinSearchUnified/tests/PluginTest.php
Labels: enhancement, next release

#163 Develop
  .travis.yml
  FinSearchUnified/Bundles/FacetResult/ColorPickerFacetResult.php
  FinSearchUnified/Bundles/FindologicFacetGateway.php
  FinSearchUnified/Bundles/ProductNumberSearch.php
  FinSearchUnified/BusinessLogic/FindologicArticleFactory.php
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Components/ProductStream/Repository.php
  FinSearchUnified/Constants.php
  FinSearchUnified/Controllers/Api/Findologic.php
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Subscriber/Api.php
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Subscriber/RegisterComponents.php
  FinSearchUnified/Subscriber/ServiceSubscriber.php
  FinSearchUnified/XmlInformation.php
  FinSearchUnified/composer.json
  FinSearchUnified/composer.lock
  FinSearchUnified/phpunit.xml.dist
  FinSearchUnified/shopware-phpcs.xml
  FinSearchUnified/tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/tests/Functional/Bootstrap.php
  FinSearchUnified/tests/Helper/StaticHelperTest.php
  FinSearchUnified/tests/PluginTest.php
Labels: next release
