Repository findologic/plugin-shopware-5, pull requests merged in 2019-08, with the labels that each got.

#240 Sw 281 facet handler image filter
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandlerTest.php
Labels: enhancement, next release

#239 SW-282-facet-handler-color-filter
  FinSearchUnified/Bundle/SearchBundle/FacetResult/ColorListItem.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandlerTest.php
Labels: enhancement, next release

#236 Sw 279 facet handler category filter
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandlerTest.php
Labels: enhancement, next release

#242 Sw 292 prepare travis for 5.6
  .travis.yml
Labels: enhancement, next release

#243 SW-293-add-base-class-for-tests
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundle/CriteriaRequestHandler/SdymCriteriaRequestHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SimpleConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/TextFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/NavigationQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SearchQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/Tests/ShopwareProcessTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
  FinSearchUnified/Tests/Subscriber/WidgetsTest.php
  FinSearchUnified/Tests/TestCase.php
Labels: enhancement, next release

#246 SW-295-fix-broken-subscriber-tests
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
  FinSearchUnified/Tests/Subscriber/SubscriberTestCase.php
  FinSearchUnified/Tests/Subscriber/WidgetsTest.php
Labels: enhancement, next release

#245 SW-294-fix-product-export
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
Labels: enhancement, next release

#248 SW-301 Fix warnings from Shopware store
  FinSearchUnified/Bundle/FacetResult/ColorListItem.php
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Components/ProductStream/CriteriaFactory.php
  FinSearchUnified/Resources/views/frontend/_resources/css/smartsuggest.css
Labels: enhancement, next release

#247 SW-300 Fix a fatal PHP error when handling Product Stream categories
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#244 SW-290 Support Shopware 5.6
  .travis.yml
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundle/CriteriaRequestHandler/SdymCriteriaRequestHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SimpleConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/TextFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/NavigationQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SearchQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/Tests/ShopwareProcessTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
  FinSearchUnified/Tests/Subscriber/SubscriberTestCase.php
  FinSearchUnified/Tests/Subscriber/WidgetsTest.php
  FinSearchUnified/Tests/TestCase.php
Labels: enhancement, next release

#251 Sw 302 encode product url
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
Labels: bug, next release

#252 SW-298-handle-special-characters-in-keywords
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
Labels: bug, next release

#254 SW-299 Add redirect function for old urls
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: enhancement, next release

#250 SW-297 whitelist checkout requests
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: bug, next release

#253 SW-296-delete-legacy-code
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: next release
