Repository findologic/plugin-shopware-5, pull requests merged in 2019-04, with the labels that each got.

#204 SW-254-findologic-search-inactive-default
  FinSearchUnified/Resources/config.xml
Labels: enhancement, next release

#203 SW-255-fix-live-reloading
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Subscriber/Widgets.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
  FinSearchUnified/Tests/Subscriber/WidgetsTest.php
Labels: bug, next release

#202 SW-256-export-product-stream-for-categories-with-children
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Tests/ShopwareProcessTest.php
Labels: bug, next release

#206 SW-259 Use PHP's rawurldecode function
  FinSearchUnified/Helper/UrlBuilder.php
Labels: bug, next release

#207 (SW-260) Export options without translations
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#205 Sw 239 querybuilder factory productnumbersearch
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilderFactory.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderTest.php
Labels: enhancement, next release

#211 SW-257 legacy export compatibility
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundle/Condition/HasActiveCategoryCondition.php
  FinSearchUnified/Bundle/SearchBundle/Condition/IsChildOfShopCategoryCondition.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilderFactory.php
  FinSearchUnified/BusinessLogic/Export.php
  FinSearchUnified/BusinessLogic/ExportFactory.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services/services.xml
  FinSearchUnified/Tests/BusinessLogic/ExportFactoryTest.php
Labels: enhancement

#210 SW-265 Fix infinite scrolling
  FinSearchUnified/Subscriber/Widgets.php
Labels: bug, next release

#212 SW-268 Don't hide Shopware's Autocomplete
  FinSearchUnified/Resources/views/frontend/_resources/css/smartsuggest.css
Labels: bug, next release

#209 Separate querybuilder for navigation and search
  FinSearchUnified/Bundle/SearchBundleFindologic/NavigationQueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilderFactory.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SearchQueryBuilder.php
  FinSearchUnified/Resources/views/frontend/search/fuzzy.tpl
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/NavigationQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SearchQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/Subscriber/WidgetsTest.php
Labels: enhancement, next release
