Repository findologic/plugin-shopware-5, pull requests merged in 2019-03, with the labels that each got.

#189 Sw 245 correctly decode smart suggest parameter
  FinSearchUnified/Subscriber/Frontend.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: bug, next release

#192 SW-247-set-output-adapter
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: bug, next release

#194 SW-246-do-not-default-to-api
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: bug, next release

#191 SW-252 Gracefully handle vendors without names during export
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Helper/Utility.php
Labels: bug, next release

#196 SW-253-fix-urlbuilder-in-customfacetgateway
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
Labels: bug, next release

#197 SW-250-missing-methods-in-querybuilder
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandlerInterface.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandlerInterface.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandlerTest.php
Labels: enhancement, future release

#193 SW-248-fix-sitemap-generation-backend
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
Labels: bug, next release

#188 Sw 238 querybuilder for productnumbersearch
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandlerInterface.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/SortingHandlerInterface.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/CategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PopularitySortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/PriceSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ProductNameSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SortingHandler/ReleaseDateSortingHandlerTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
Labels: enhancement, next release

#173 Sw 217 implement smart did you mean
  .travis.yml
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Constants.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Resources/snippets/frontend/search/fuzzy.ini
  FinSearchUnified/Resources/views/frontend/search/fuzzy.tpl
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: enhancement, next release
