Repository findologic/plugin-shopware-5, pull requests merged in 2019-05, with the labels that each got.

#216 SW-263 dont add local changes to archive
  archive.sh
Labels: enhancement, next release

#215 SW-266-dont-handle-emotion-banners
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#214 SW-261 support multiple range sliders
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: bug, next release

#218 Sw 270 refactor mode custom listing hydrator
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydrator.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
Labels: next release

#219 Sw 267 querybuilderfactory for requests
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilderFactory.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SearchQueryBuilderTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: enhancement, next release

#222 Fixed typo in snippet
  FinSearchUnified/Resources/snippets/frontend/search/fuzzy.ini
Labels: bug, next release

#221 SW-277 copy relevant legacy code
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/PriceConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilder.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/SearchTermConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/SearchQueryBuilderTest.php
Labels: enhancement, next release
