Repository findologic/plugin-shopware-5, pull requests merged in 2019-02, with the labels that each got.

#175 Sw 224 create querybuilder factory
  FinSearchUnified/Bundles/SearchBundleDBAL/QueryBuilderFactory.php
  FinSearchUnified/Resources/services/services.xml
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Helper/Utility.php
Labels: enhancement

#180 Sw 234 use findologic querybuilder factory
  FinSearchUnified/Bundles/SearchBundleDBAL/QueryBuilderFactory.php
  FinSearchUnified/BusinessLogic/Export.php
  FinSearchUnified/Resources/services/services.xml
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/ConditionHandler/HasActiveCategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/ConditionHandler/HasActiveMainDetailConditionHandlerTest.php
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/ConditionHandler/HasProductNameConditionHandlerTest.php
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/ConditionHandler/IsActiveProductConditionHandlerTest.php
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/ConditionHandler/IsChildOfShopCategoryConditionHandlerTest.php
  FinSearchUnified/Tests/Bundles/SearchBundleDBAL/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/BusinessLogic/ExportTest.php
  FinSearchUnified/Tests/TestBase.php
Labels: enhancement, future release

#181 Use correct smarty variable for usergroup hash in smart suggest snippet
  FinSearchUnified/Resources/views/frontend/fin_search_unified/header.tpl
  README.md
Labels: bug, next release

#177 SW-228 get client IP from proxy
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
Labels: bug, next release

#182 Optimize configuration export
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
Labels: bug, next release

#174 Sw 223 hydrator facet gateway
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydrator.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: enhancement, next release

#171 SW-221 create facet hydrator
  FinSearchUnified/Bundle/FacetResult/ColorListItem.php
  FinSearchUnified/Bundle/FacetResult/ColorPickerFacetResult.php
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydrator.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Helper/UrlBuilder.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/UrlBuilderTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/Tests/Subscriber/FrontendTest.php
Labels: enhancement, next release

#184 Remove any logic from the update process
  FinSearchUnified/FinSearchUnified.php
Labels: bug, next release
