Repository findologic/plugin-shopware-5, pull requests merged in 2020-02, with the labels that each got.

#294 SW-389_fix_empty_values
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#293 SW-388_elasticsearch
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Resources/shopware/searchBundleES.xml
Labels: bug, next release

#291 SW-385 Make Product Stream preview great again
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#290 SW-383 Fix filters on browserback
  FinSearchUnified/Bundle/SearchBundle/CriteriaRequestHandler/FindologicFacetCriteriaRequestHandler.php
Labels: bug, next release

#296 SW-377-exclude-products-with-cross-sell-category
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/PluginTest.php
Labels: enhancement

#292 Sw 384 filters should be updated page reloaded
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/TextFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/QueryBuilderFactory.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/Helper/Utility.php
  FinSearchUnified/Tests/MockData/XMLResponse/demoResponse.xml
Labels: bug, next release

#300 SW-366_exclude_cross_sell_categories
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Resources/config.xml
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
  FinSearchUnified/Tests/PluginTest.php
Labels: enhancement, next release

#298 SW-390_fix_slider_issues
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandler.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandlerTest.php
Labels: bug, next release

#297 SW-343-export-boolean-fields
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
Labels: enhancement, next release

#278 Sw 286 smart suggest result should consider inactive filters
  FinSearchUnified/Bundle/SearchBundle/CriteriaRequestHandler/FindologicFacetCriteriaRequestHandler.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydrator.php
  FinSearchUnified/Components/ConfigLoader.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydratorTest.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#299 SW-392 Fix check for inactive variants
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
Labels: bug, next release
