Repository findologic/plugin-shopware-5, pull requests merged in 2020-01, with the labels that each got.

#276 Sw 358 configuring empty attribute values must not break the export
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
Labels: bug, next release

#281 Sw 364 export should not fail due to empty value
  FinSearchUnified/BusinessLogic/FindologicArticleFactory.php
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/ShopwareProcess.php
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
  FinSearchUnified/Tests/Components/ProductStream/CriteriaFactoryTest.php
  FinSearchUnified/Tests/Components/ProductStream/RepositoryTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/PluginTest.php
  FinSearchUnified/composer.json
Labels: bug, next release

#269 SW-245 sw52 support
  .travis.yml
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundle/Condition/Operator.php
  FinSearchUnified/Bundle/SearchBundle/Condition/ProductAttributeCondition.php
  FinSearchUnified/Bundle/SearchBundle/CriteriaRequestHandler/FindologicFacetCriteriaRequestHandler.php
  FinSearchUnified/Bundle/SearchBundleES/Subscriber/ServiceSubscriber.php
  FinSearchUnified/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandler.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/CustomFacetGatewayInterface.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGateway.php
  FinSearchUnified/Bundle/StoreFrontBundle/Gateway/Findologic/Hydrator/CustomListingHydrator.php
  FinSearchUnified/Bundle/StoreFrontBundle/Service/Core/CustomFacetService.php
  FinSearchUnified/Bundle/StoreFrontBundle/Service/CustomFacetServiceInterface.php
  FinSearchUnified/Bundle/StoreFrontBundle/Struct/Search/CustomFacet.php
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/FinSearchUnified.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Resources/shopware/searchBundleES.xml
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundle/Condition/ProductAttributeConditionTest.php
  FinSearchUnified/Tests/Bundle/SearchBundle/CriteriaRequestHandler/FindologicFacetCriteriaRequestHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/ConditionHandler/ProductAttributeConditionHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/TextFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/QueryBuilderFactoryTest.php
  FinSearchUnified/Tests/Bundle/StoreFrontBundle/Gateway/Findologic/CustomFacetGatewayTest.php
  FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/plugin.xml
Labels: enhancement, future release

#280 Sw 346 clear cache when configuration changes
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Subscriber/CacheSubscriber.php
  FinSearchUnified/Tests/Subscriber/CacheSubscriberTest.php
Labels: enhancement, next release

#283 SW-344-redirect-shopware-search-api-failure
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: bug, next release

#279 SW-303_use_facet_handlers
  FinSearchUnified/Bundle/FacetResult/ColorListItem.php
  FinSearchUnified/Bundle/FacetResult/ColorPickerFacetResult.php
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandler.php
  FinSearchUnified/Bundle/SearchBundleFindologic/FacetHandler/TextFacetHandler.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Resources/services.xml
  FinSearchUnified/Tests/Bundle/ProductNumberSearchTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/CategoryFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ColorFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/ImageFacetHandlerTest.php
  FinSearchUnified/Tests/Bundle/SearchBundleFindologic/FacetHandler/RangeFacetHandlerTest.php
  FinSearchUnified/Tests/Functional/Controllers/Frontend/FinSearchUnified_Tests_Controllers_Frontend_SearchTest.php
  FinSearchUnified/Tests/Helper/StaticHelperTest.php
Labels: enhancement, next release

#286 SW-375-fix-warnings-shopware-code-review
  FinSearchUnified/Bundle/ProductNumberSearch.php
  FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
  FinSearchUnified/Helper/StaticHelper.php
  FinSearchUnified/Tests/Components/ConfigLoaderTest.php
Labels: enhancement, next release

#287 SW-376-add-config-field-cross-sell-categories
  FinSearchUnified/Resources/config.xml
Labels: enhancement
